### ISSUE TITLE
May I ask how to debug it???  My dataset problem or?

### ISSUE THREAD

**Issue by marcusau** [mtreviso/deeptagger#1]
[2020-01-09 09:36:25.625] INFO: Running with options: 

Namespace(add_embeddings_vocab=False, 
alpha=None, amsgrad=False, beta0=None, beta1=None, bidirectional=True, 

caps_embeddings_size=50, conv_size=100, debug=False, 

decay_steps=None, del_tag='/', del_word=' ', dev_batch_size=128, dev_checkpoint_epochs=1, 

dev_path='/home/ubuntu/deeptagger/data/dev.txt', dropout=0.5, early_stopping_patience=3, 

emb_dropout=0.4, embeddings_format=None, embeddings_path=None, epochs=3, 

eta_min=1e-07, final_report=True, freeze_embeddings=False, gamma=0.1, gpu_id=None, 

hidden_size=[100], keep_rare_with_vectors=False, kernel_size=7,

learning_rate=None, load=None, loss_weights='same', lr_decay=None, lr_step_decay=None, 

max_length=1000000000000, min_length=0, model='rcnn', momentum=None, nesterov=False, 

optimizer='adam', output_dir='/home/ubuntu/deeptagger/logs', pool_length=3, 

prediction_type='classes', prefix_embeddings_size=50, prefix_max_length=5, prefix_min_length=1, 

restore_best_model=False, resume_epoch=None, rho=None, rnn_type='lstm', 

save='/home/ubuntu/deeptagger/models', save_best_only=False, save_checkpoint_epochs=1, 

scheduler=None, seed=42, shuffle=True, step_size=None, suffix_embeddings_size=50, 

suffix_max_length=5, suffix_min_length=1, sum_bidir=False, t_max=None, tensorboard=False, 

test_path=None, text=None, train_batch_size=128, train_path='/home/ubuntu/deeptagger/data/train.txt',

 use_caps=False, use_prefixes=True, use_suffixes=True, vocab_min_frequency=1, vocab_size=None, warmup_steps=None, weight_decay=None, word_embeddings_size=100)

[2020-01-09 09:36:25.626] INFO: Building train corpus: /home/ubuntu/deeptagger/data/train.txt
[2020-01-09 09:37:26.600] INFO: Building train iterator...
[2020-01-09 09:37:26.600] INFO: Building dev dataset: /home/ubuntu/deeptagger/data/dev.txt
[2020-01-09 09:37:41.296] INFO: Building dev iterator...
[2020-01-09 09:37:41.296] INFO: Building vocabulary...
[2020-01-09 09:38:00.492] INFO: Building model...
[2020-01-09 09:38:00.841] INFO: Building optimizer...
[2020-01-09 09:38:00.841] INFO: Building scheduler...
[2020-01-09 09:38:00.841] INFO: Word vocab size: 172060
[2020-01-09 09:38:00.842] INFO: Tag vocab size: 77
[2020-01-09 09:38:00.842] INFO: Number of training examples: 265235
[2020-01-09 09:38:00.842] INFO: Number of dev examples: 66309
[2020-01-09 09:38:00.842] INFO: Model info: 
[2020-01-09 09:38:00.842] INFO: RCNN(
  (handcrafted): HandCrafted(
    (prefixes_emb): Embedding(239522, 50, padding_idx=1)
    (suffixes_emb): Embedding(242414, 50, padding_idx=1)
  )
  (word_emb): Embedding(172060, 100, padding_idx=1)
  (dropout_emb): Dropout(p=0.4, inplace=False)
  (cnn_1d): Conv1d(600, 100, kernel_size=(7,), stride=(1,), padding=(3,))
  (max_pool): MaxPool1d(kernel_size=3, stride=3, padding=1, dilation=1, ceil_mode=False)
  (rnn): LSTM(600, 100, batch_first=True, bidirectional=True)
  (dropout_rnn): Dropout(p=0.5, inplace=False)
  (linear_out): Linear(in_features=200, out_features=77, bias=True)
  (relu): ReLU()
  (sigmoid): Sigmoid()
  (_loss): NLLLoss()
)
[2020-01-09 09:38:00.843] INFO: Optimizer info: 
[2020-01-09 09:38:00.843] INFO: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.001
    lr: 0.001
    weight_decay: 0
)
[2020-01-09 09:38:00.843] INFO: Scheduler info: 
[2020-01-09 09:38:00.843] INFO: <deeptagger.modules.optim.lr_scheduler.FakeLR object at 0x7f0109cb6be0>
[2020-01-09 09:38:00.843] INFO: Building trainer...
[2020-01-09 09:38:00.843] INFO: Evaluating before training...
Traceback (most recent call last):
  File "/home/ubuntu/deeptagger/Train.py", line 41, in <module>
    tagger.train(**args)
  File "/home/ubuntu/deeptagger/deeptagger/tagger.py", line 99, in train
    fields_tuples, model, optim, sched = train.run(self.options)
  File "/home/ubuntu/deeptagger/deeptagger/train.py", line 106, in run
    trainer.train()
  File "/home/ubuntu/deeptagger/deeptagger/trainer.py", line 57, in train
    self.dev_epoch()
  File "/home/ubuntu/deeptagger/deeptagger/trainer.py", line 141, in dev_epoch
    self._eval(self.dev_iter, self.dev_stats)
  File "/home/ubuntu/deeptagger/deeptagger/trainer.py", line 187, in _eval
    pred = self.model(batch)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/deeptagger/deeptagger/models/rcnn.py", line 160, in forward
    h, self.hidden = self.rnn(h, self.hidden)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 562, in forward
    return self.forward_packed(input, hx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 554, in forward_packed
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 523, in forward_impl
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 496, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 149, in check_input
    self.input_size, input.size(-1)))
RuntimeError: input.size(-1) must be equal to input_size. Expected 600, got 34

Process exited with code: 1

my command is :

# -*- coding: utf-8 -*-
import glob
import os
import re
import numpy
import pandas
from deeptagger import Tagger

master_folder=r'/home/ubuntu/deeptagger'
data_folder=master_folder+'/'+ 'data'
model_folder = master_folder+'/'+'models'
log_folder = master_folder +'/logs'

args = {
  'train_path': data_folder+'/train.txt',
  'dev_path': data_folder+'/dev.txt',
  'del_word': ' ',
  'del_tag': '/',
  'model': 'rcnn',
  'rnn_type': 'lstm',
  'bidirectional': True,
  'train_batch_size': 128,
  'dev_batch_size': 128,
  'optimizer': 'adam',
  'final_report': True,
  'epochs': 3,
  'use_prefixes': True,
  'use_suffixes': True,
  'use_caps': False,
   'shuffle': True,
  'early_stopping_patience': 3,
  'restore_best_model': False,  # 
   'gpu_id': '0',
  'save_best_only': False, # only save the model
  
  'output_dir': log_folder,  # keep log information
  'save': model_folder,  # save models
}

tagger = Tagger()
tagger.train(**args)

**Comment by mtreviso** [comment]
Hi! Inserting this before line 79 in `rcnn.py` should do the trick:

```
features_size = int((options.conv_size + 2 * (options.pool_length // 2) - (options.pool_length - 1) - 1) / options.pool_length + 1)
```

**Comment by marcusau** [comment]
Hi,   

    I have followed your instructions and added the code "features_size = int((options.conv_size + 2 * (options.pool_length // 2) - (options.pool_length - 1) - 1) / options.pool_length + 1)"   before line 79 in rcnn.py

![image](https://user-images.githubusercontent.com/31444195/72229919-fcea7800-35ec-11ea-8fb0-7a48361288b0.png)


   It still does not work. New error emerges:






[2020-01-13 02:07:21.189] INFO: Running with options: Namespace(add_embeddings_vocab=False, alpha=None, amsgrad=False, beta0=None, beta1=None, bidirectional=True, caps_embeddings_size=50, conv_size=100, debug=False, decay_steps=None, del_tag='/', del_word=' ', dev_batch_size=128, dev_checkpoint_epochs=1, dev_path='/home/ubuntu/deeptagger/data/dev.txt', dropout=0.5, early_stopping_patience=3, emb_dropout=0.4, embeddings_format=None, embeddings_path=None, epochs=3, eta_min=1e-07, final_report=True, freeze_embeddings=False, gamma=0.1, gpu_id=None, hidden_size=[100], keep_rare_with_vectors=False, kernel_size=3, learning_rate=None, load=None, loss_weights='same', lr_decay=None, lr_step_decay=None, max_length=1000000000000, min_length=0, model='rcnn', momentum=None, nesterov=False, optimizer='adam', output_dir='/home/ubuntu/deeptagger/logs', pool_length=3, prediction_type='classes', prefix_embeddings_size=50, prefix_max_length=5, prefix_min_length=1, restore_best_model=False, resume_epoch=None, rho=None, rnn_type='lstm', save='/home/ubuntu/deeptagger/models', save_best_only=False, save_checkpoint_epochs=1, scheduler=None, seed=42, shuffle=True, step_size=None, suffix_embeddings_size=50, suffix_max_length=5, suffix_min_length=1, sum_bidir=False, t_max=None, tensorboard=False, test_path=None, text=None, train_batch_size=128, train_path='/home/ubuntu/deeptagger/data/train.txt', use_caps=False, use_prefixes=True, use_suffixes=True, vocab_min_frequency=1, vocab_size=None, warmup_steps=None, weight_decay=None, word_embeddings_size=100)
[2020-01-13 02:07:21.190] INFO: Building train corpus: /home/ubuntu/deeptagger/data/train.txt
[2020-01-13 02:08:22.443] INFO: Building train iterator...
[2020-01-13 02:08:22.443] INFO: Building dev dataset: /home/ubuntu/deeptagger/data/dev.txt
[2020-01-13 02:08:37.098] INFO: Building dev iterator...
[2020-01-13 02:08:37.099] INFO: Building vocabulary...
[2020-01-13 02:08:55.847] INFO: Building model...
[2020-01-13 02:08:56.171] INFO: Building optimizer...
[2020-01-13 02:08:56.171] INFO: Building scheduler...
[2020-01-13 02:08:56.172] INFO: Word vocab size: 172060
[2020-01-13 02:08:56.172] INFO: Tag vocab size: 77
[2020-01-13 02:08:56.172] INFO: Number of training examples: 265235
[2020-01-13 02:08:56.172] INFO: Number of dev examples: 66309
[2020-01-13 02:08:56.172] INFO: Model info: 
[2020-01-13 02:08:56.172] INFO: RCNN(
  (handcrafted): HandCrafted(
    (prefixes_emb): Embedding(239522, 50, padding_idx=1)
    (suffixes_emb): Embedding(242414, 50, padding_idx=1)
  )
  (word_emb): Embedding(172060, 100, padding_idx=1)
  (dropout_emb): Dropout(p=0.4, inplace=False)
  (cnn_1d): Conv1d(600, 100, kernel_size=(3,), stride=(1,), padding=(1,))
  (max_pool): MaxPool1d(kernel_size=3, stride=3, padding=1, dilation=1, ceil_mode=False)
  (rnn): LSTM(34, 100, batch_first=True, bidirectional=True)
  (dropout_rnn): Dropout(p=0.5, inplace=False)
  (linear_out): Linear(in_features=200, out_features=77, bias=True)
  (relu): ReLU()
  (sigmoid): Sigmoid()
  (_loss): NLLLoss()
)
[2020-01-13 02:08:56.172] INFO: Optimizer info: 
[2020-01-13 02:08:56.173] INFO: Adam (
Parameter Group 0
    betas: (0.9, 0.999)
    eps: 1e-08
    initial_lr: 0.001
    lr: 0.001
    weight_decay: 0
)
[2020-01-13 02:08:56.173] INFO: Scheduler info: 
[2020-01-13 02:08:56.173] INFO: <deeptagger.modules.optim.lr_scheduler.FakeLR object at 0x7fb58008ccf8>
[2020-01-13 02:08:56.173] INFO: Building trainer...
[2020-01-13 02:08:56.173] INFO: Evaluating before training...
Traceback (most recent call last):
  File "/home/ubuntu/deeptagger/Train.py", line 42, in <module>
    tagger.train(**args)
  File "/home/ubuntu/deeptagger/deeptagger/tagger.py", line 99, in train
    fields_tuples, model, optim, sched = train.run(self.options)
  File "/home/ubuntu/deeptagger/deeptagger/train.py", line 106, in run
    trainer.train()
  File "/home/ubuntu/deeptagger/deeptagger/trainer.py", line 57, in train
    self.dev_epoch()
  File "/home/ubuntu/deeptagger/deeptagger/trainer.py", line 141, in dev_epoch
    self._eval(self.dev_iter, self.dev_stats)
  File "/home/ubuntu/deeptagger/deeptagger/trainer.py", line 187, in _eval
    pred = self.model(batch)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/deeptagger/deeptagger/models/rcnn.py", line 171, in forward
    h = self.dropout_gru(h)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'RCNN' object has no attribute 'dropout_gru'


Process exited with code: 1



For your information, i show you my config here:

# -*- coding: utf-8 -*-
import glob
import os
import re
import numpy
import pandas
from deeptagger import Tagger

master_folder=r'/home/ubuntu/deeptagger'
data_folder=master_folder+'/'+ 'data'
model_folder = master_folder+'/'+'models'
log_folder = master_folder +'/logs'

args = {
  'train_path': data_folder+'/train.txt',
  'dev_path': data_folder+'/dev.txt',
  'del_word': ' ',
  'del_tag': '/',
  'model': 'rcnn',
  'rnn_type': 'lstm',
  'bidirectional': True,
  'train_batch_size': 128,
  'dev_batch_size': 128,
  'optimizer': 'adam',
  'final_report': True,
  'epochs': 3,
  'use_prefixes': True,
  'use_suffixes': True,
  'use_caps': False,
   'shuffle': True,
  'early_stopping_patience': 3,
  'restore_best_model': False,  # 
   'gpu_id': '0',
   'kernel_size' :3,
  'save_best_only': False, # only save the model
  
  'output_dir': log_folder,  # keep log information
  'save': model_folder,  # save models
}

tagger = Tagger()

**Comment by marcusau** [comment]
Also in my config,  args = { } ,   i added 'gpu_id': '0', to define the serial numbers of gpu, however the algo cannot detect that ::

[2020-01-13 02:07:21.189] INFO: Running with options: Namespace(add_embeddings_vocab=False, alpha=None, amsgrad=False, beta0=None, beta1=None, bidirectional=True, caps_embeddings_size=50, conv_size=100, debug=False, decay_steps=None, del_tag='/', del_word=' ', dev_batch_size=128, dev_checkpoint_epochs=1, dev_path='/home/ubuntu/deeptagger/data/dev.txt', dropout=0.5, early_stopping_patience=3, emb_dropout=0.4, embeddings_format=None, embeddings_path=None, epochs=3, eta_min=1e-07, final_report=True, freeze_embeddings=False, gamma=0.1,  **gpu_id=None**, hidden_size=[100], keep_rare_with_vectors=False, kernel_size=3, learning_rate=None, load=None, loss_weights='same', lr_decay=None, lr_step_decay=None, max_length=1000000000000, min_length=0, model='rcnn', momentum=None, nesterov=False, optimizer='adam', output_dir='/home/ubuntu/deeptagger/logs', pool_length=3, prediction_type='classes', prefix_embeddings_size=50, prefix_max_length=5, prefix_min_length=1, restore_best_model=False, resume_epoch=None, rho=None, rnn_type='lstm', save='/home/ubuntu/deeptagger/models', save_best_only=False, save_checkpoint_epochs=1, scheduler=None, seed=42, shuffle=True, step_size=None, suffix_embeddings_size=50, suffix_max_length=5, suffix_min_length=1, sum_bidir=False, t_max=None, tensorboard=False, test_path=None, text=None, train_batch_size=128, train_path='/home/ubuntu/deeptagger/data/train.txt', use_caps=False, use_prefixes=True, use_suffixes=True, vocab_min_frequency=1, vocab_size=None, warmup_steps=None, weight_decay=None, word_embeddings_size=100)

**Comment by sazzy4o** [comment]
In case anyone runs into these issues in future

1. Use `torchtext==0.6.0` if you have import issues

2. `RuntimeError: input.size(-1) must be equal to input_size.`
See: https://github.com/mtreviso/deeptagger/issues/1#issuecomment-572949332 for

3. `AttributeError: 'RCNN' object has no attribute 'dropout_gru'`
Change `rcnn` to `simple_lstm` in the config/args
